
export const PLATOS_MENU = 'PLATOS_MENU';

export const AGREGAR_PLATO = 'AGREGAR_PLATO';
export const OBTENER_PLATOS = 'OBTENER_PLATOS';
export const VALIDAR_PLATO = 'VALIDAR_PLATO';
export const ELIMINAR_PLATO = 'ELIMINAR_PLATO';
export const PLATO_ACTUAL = 'PLATO_ACTUAL';
export const ACTUALIZAR_PLATO = 'ACTUALIZAR_PLATO';
export const LIMPIAR_PLATO = 'LIMPIAR_PLATO';

export const PLATO_ERROR = 'PLATO_ERROR';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';
